name: CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Node.js Setup
    - uses: actions/setup-node@v2
      with:
       node-version: '14'
      
    - name: Building Node packages
      run: |
        npm install
        npm run build
    
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: /
        remote_path: /var/www/a18eliek/
        remote_host: ${{ secrets.SERVER }}
        remote_port: ${{ secrets.PORT }}
        remote_user: ${{ secrets.USER }}
        remote_key: ${{ secrets.KEY }}
